#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-Amelia
Version  : 1.7.5
Release  : 9
URL      : https://cran.r-project.org/src/contrib/Amelia_1.7.5.tar.gz
Source0  : https://cran.r-project.org/src/contrib/Amelia_1.7.5.tar.gz
Summary  : A Program for Missing Data
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-Amelia-lib = %{version}-%{release}
BuildRequires : R-Rcpp
BuildRequires : R-RcppArmadillo
BuildRequires : buildreq-R

%description
##################################################
##                                              ##
## Amelia II: A Package for Missing Data        ##
##                                              ##
## James Honaker <jhonaker@iq.harvard.edu.edu>  ##
## Gary King <king@harvard.edu>                 ##
## Matthew Blackwell <m.blackwel@rochester.edu> ##
##                                              ##
##################################################

%package lib
Summary: lib components for the R-Amelia package.
Group: Libraries

%description lib
lib components for the R-Amelia package.


%prep
%setup -q -c -n Amelia

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552710567

%install
export SOURCE_DATE_EPOCH=1552710567
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Amelia
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Amelia
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Amelia
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  Amelia || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/Amelia/CITATION
/usr/lib64/R/library/Amelia/DESCRIPTION
/usr/lib64/R/library/Amelia/INDEX
/usr/lib64/R/library/Amelia/Meta/Rd.rds
/usr/lib64/R/library/Amelia/Meta/data.rds
/usr/lib64/R/library/Amelia/Meta/features.rds
/usr/lib64/R/library/Amelia/Meta/hsearch.rds
/usr/lib64/R/library/Amelia/Meta/links.rds
/usr/lib64/R/library/Amelia/Meta/nsInfo.rds
/usr/lib64/R/library/Amelia/Meta/package.rds
/usr/lib64/R/library/Amelia/Meta/vignette.rds
/usr/lib64/R/library/Amelia/NAMESPACE
/usr/lib64/R/library/Amelia/NEWS
/usr/lib64/R/library/Amelia/R/Amelia
/usr/lib64/R/library/Amelia/R/Amelia.rdb
/usr/lib64/R/library/Amelia/R/Amelia.rdx
/usr/lib64/R/library/Amelia/data/africa.RData
/usr/lib64/R/library/Amelia/data/freetrade.RData
/usr/lib64/R/library/Amelia/doc/amelia.R
/usr/lib64/R/library/Amelia/doc/amelia.Rnw
/usr/lib64/R/library/Amelia/doc/amelia.pdf
/usr/lib64/R/library/Amelia/doc/index.html
/usr/lib64/R/library/Amelia/gui/action_go.gif
/usr/lib64/R/library/Amelia/gui/action_save.gif
/usr/lib64/R/library/Amelia/gui/action_stop.gif
/usr/lib64/R/library/Amelia/gui/amelia.ico
/usr/lib64/R/library/Amelia/gui/arrow_down.gif
/usr/lib64/R/library/Amelia/gui/arrow_left.gif
/usr/lib64/R/library/Amelia/gui/arrow_up.gif
/usr/lib64/R/library/Amelia/gui/flag_red.gif
/usr/lib64/R/library/Amelia/gui/gallery19.gif
/usr/lib64/R/library/Amelia/gui/gallery19.jpg
/usr/lib64/R/library/Amelia/gui/histogram.gif
/usr/lib64/R/library/Amelia/gui/icon_accept.gif
/usr/lib64/R/library/Amelia/gui/icon_clock.gif
/usr/lib64/R/library/Amelia/gui/icon_user.gif
/usr/lib64/R/library/Amelia/gui/icon_world.gif
/usr/lib64/R/library/Amelia/gui/page-R.gif
/usr/lib64/R/library/Amelia/gui/page.gif
/usr/lib64/R/library/Amelia/gui/page_dta.gif
/usr/lib64/R/library/Amelia/gui/page_edit.gif
/usr/lib64/R/library/Amelia/gui/page_sas.gif
/usr/lib64/R/library/Amelia/gui/page_spss.gif
/usr/lib64/R/library/Amelia/gui/page_text.gif
/usr/lib64/R/library/Amelia/gui/page_up.gif
/usr/lib64/R/library/Amelia/gui/table.gif
/usr/lib64/R/library/Amelia/help/Amelia.rdb
/usr/lib64/R/library/Amelia/help/Amelia.rdx
/usr/lib64/R/library/Amelia/help/AnIndex
/usr/lib64/R/library/Amelia/help/aliases.rds
/usr/lib64/R/library/Amelia/help/paths.rds
/usr/lib64/R/library/Amelia/html/00Index.html
/usr/lib64/R/library/Amelia/html/R.css
/usr/lib64/R/library/Amelia/test/transform.R
/usr/lib64/R/library/Amelia/tests/bounds.R
/usr/lib64/R/library/Amelia/tests/moPrep-test.R
/usr/lib64/R/library/Amelia/tests/overimp.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/Amelia/libs/Amelia.so
/usr/lib64/R/library/Amelia/libs/Amelia.so.avx2
/usr/lib64/R/library/Amelia/libs/Amelia.so.avx512
